- name: Uninstall old versions of docker and docker-compose on centos
  yum:
    name:
       - docker-client
       - docker-client-latest
       - docker-common
       - docker-latest
       - docker-latest-logrotate
       - docker-logrotate
       - docker-engine
    state: absent

- name: Configuring Repository
  yum:
    name:
       - yum-utils
    state: latest

- name: Adding docker repository 
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    
- name: Enable Docker CE Nightly Repo
  ini_file:
     dest: /etc/yum.repos.d/docker-ce.repo
     section: 'docker-ce-nightly'
     option: enabled
     value: 0
