---
- hosts: localhost
  become: yes

  tasks:
    - include: tasks/centos.yml
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - include: tasks/ubuntu.yml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
